# Generated by Django 6.0.5 on 2026-05-13 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Em andamento', 'Em andamento'), ('Em risco', 'Em risco'), ('Pausado', 'Pausado'), ('Concluído', 'Concluído')], default='Planejado', max_length=40)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('real_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('progress', models.IntegerField(default=0)),
                ('start_at', models.DateField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
