# Generated by Django 4.0.3 on 2026-05-26 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planejado', 'Planejado'), ('Em andamento', 'Em andamento'), ('Em risco', 'Em risco'), ('Pausado', 'Pausado'), ('Concluido', 'Concluido')], default='Planejado', max_length=40),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('LIDER', 'Lider'), ('DESENVOLVEDOR', 'Desenvolvedor'), ('ANALISTA', 'Analista'), ('TESTER', 'Tester'), ('OBSERVADOR', 'Observador'), ('CLIENTE_APROVADOR', 'Cliente aprovador'), ('PRODUCT_OWNER', 'Product owner'), ('SCRUM_MASTER', 'Scrum master'), ('SUPORTE', 'Suporte'), ('OUTRO', 'Outro')], default='DESENVOLVEDOR', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project__name', 'user__username'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
