# Generated by Django 5.2.15 on 2026-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_contact_principal_alter_project_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="health",
            field=models.CharField(
                choices=[
                    ("on_track", "No prazo"),
                    ("at_risk", "Em risco"),
                    ("delayed", "Atrasado"),
                ],
                default="on_track",
                max_length=20,
            ),
        ),
    ]
