# Generated by Django 5.2.15 on 2026-06-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_active_client_address_client_document_and_more"),
        ("projects", "0005_projectcustomfield_projectcustomvalue"),
        ("users", "0009_remove_technical_group_add_teams_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="metodologia",
            field=models.CharField(
                choices=[
                    ("scrum", "Scrum"),
                    ("kanban", "Kanban"),
                    ("hibrido", "Híbrido"),
                    ("tradicional", "Tradicional"),
                ],
                default="scrum",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tipo",
            field=models.CharField(
                choices=[("interno", "Interno"), ("cliente", "Cliente")],
                default="cliente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="clients.client",
            ),
        ),
    ]
