# Generated by Django 5.2.15 on 2026-06-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_auto_assign"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.CharField(blank=True, default="BRL", max_length=10),
        ),
        migrations.AddField(
            model_name="company",
            name="email_domain",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="company",
            name="locale",
            field=models.CharField(blank=True, default="pt-BR", max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="timezone",
            field=models.CharField(
                blank=True, default="America/Sao_Paulo", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("interno", "Uso interno"),
                    ("prestador", "Prestação de serviço (B2B)"),
                    ("hibrido", "Híbrido (interno + clientes)"),
                ],
                default="prestador",
                max_length=20,
            ),
        ),
    ]
