# Generated by Django 5.2.15 on 2026-06-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_active_client_address_client_document_and_more"),
        ("knowledge", "0003_knowledgearticle_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticle",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledge_articles",
                to="clients.client",
            ),
        ),
    ]
