# Generated by Django 6.0.5 on 2026-05-13 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Planejada', max_length=40)),
                ('start_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('story_points', models.PositiveIntegerField(default=0)),
                ('backlog', models.JSONField(blank=True, default=list)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='companies.company')),
            ],
            options={
                'ordering': ['-start_at', '-created_at'],
            },
        ),
    ]
