# Generated by Django 5.2.15 on 2026-06-24 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_auto_assign"),
        ("sprints", "0004_sprintretrospective_sprintreview"),
        ("tickets", "0012_ticket_csat_sent_at_ticket_last_reopened_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SprintTicketPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("responsible_ids", models.JSONField(blank=True, default=list)),
                (
                    "planned_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("story_points", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprint_ticket_plans",
                        to="companies.company",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_plans",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprint_plans",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("sprint", "ticket")},
            },
        ),
    ]
