# Generated by Django 5.2.15 on 2026-06-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0005_sprintticketplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprintactivityplan",
            name="complexity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (5, "5"),
                    (8, "8"),
                    (13, "13"),
                    (21, "21"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sprintactivityplan",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Crítica", "Crítica"),
                    ("Alta", "Alta"),
                    ("Média", "Média"),
                    ("Baixa", "Baixa"),
                ],
                default="Média",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sprintactivityplan",
            name="user_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sprintticketplan",
            name="complexity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (5, "5"),
                    (8, "8"),
                    (13, "13"),
                    (21, "21"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sprintticketplan",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Crítica", "Crítica"),
                    ("Alta", "Alta"),
                    ("Média", "Média"),
                    ("Baixa", "Baixa"),
                ],
                default="Média",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sprintticketplan",
            name="user_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
