# Generated by Django 5.2.15 on 2026-06-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0006_sprintactivityplan_complexity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprintticketplan",
            name="planned_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
