# Generated by Django 5.2.15 on 2026-06-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0008_add_sprint_participant"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="observations",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sprintparticipant",
            name="hours_executed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="sprintparticipant",
            name="hours_planned",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="sprintparticipant",
            name="inclusion_mode",
            field=models.CharField(
                choices=[("team", "Equipe"), ("manual", "Manual")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sprintparticipant",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sprintparticipant",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sprintparticipant",
            name="story_points_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sprintparticipant",
            name="story_points_planned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sprintparticipant",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprint_participants",
                to="teams.team",
            ),
        ),
    ]
