# Generated by Django 5.2.15 on 2026-07-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sprints",
            "0009_sprint_observations_sprintparticipant_hours_executed_and_more",
        ),
        ("teams", "0002_org_structure_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprints",
                to="teams.team",
            ),
        ),
    ]
