# Generated by Django 6.0.5 on 2026-05-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("users", "0002_user_hourly_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_users",
                to="clients.client",
            ),
        ),
    ]
