# Generated by Django 4.0.3 on 2026-05-26 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_active_client_address_client_document_and_more'),
        ('companies', '0001_initial'),
        ('users', '0003_user_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('TECHNICIAN', 'Technician'), ('CLIENT', 'Client'), ('COLLABORATOR', 'Collaborator'), ('REQUESTER', 'Requester'), ('OBSERVER', 'Observer'), ('PROJECT_LEAD', 'Project lead'), ('APPROVER', 'Approver')], default='ADMIN', max_length=30),
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organization_links', to='companies.company')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__name', 'user__username'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
