# Generated by Codex on 2026-05-26

from django.db import migrations, models
import django.db.models.deletion
import uuid


def normalize_existing_roles(apps, schema_editor):
    User = apps.get_model("users", "User")

    technician_roles = {
        "MANAGER",
        "GESTOR",
        "PROJECT_LEAD",
        "LIDER_PROJETO",
        "LIDER_DE_PROJETO",
        "COLLABORATOR",
        "COLABORADOR",
        "TECH",
        "TECNICO",
        "SUPORTE",
        "SUPPORT",
    }
    client_roles = {
        "REQUESTER",
        "SOLICITANTE",
        "OBSERVER",
        "OBSERVADOR",
        "APPROVER",
        "APROVADOR",
        "CLIENTE",
        "CUSTOMER",
    }

    for user in User.objects.all():
        role = str(user.role or "").strip().upper().replace("-", "_").replace(" ", "_")

        if role in technician_roles:
            user.role = "TECHNICIAN"
        elif role in client_roles:
            user.role = "CLIENT"
        elif role in {"ADMIN", "ADMINISTRADOR", "ADMINISTRATOR", "SUPERUSER", "SUPER_USER"}:
            user.role = "ADMIN"
        elif role not in {"TECHNICIAN", "CLIENT", "ADMIN"}:
            user.role = "CLIENT" if user.client_id else "TECHNICIAN"

        user.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0004_alter_user_role_userorganization"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionBlock",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permission_blocks", to="companies.company")),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="denied_permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="granted_permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="permission_blocks",
            field=models.ManyToManyField(blank=True, related_name="users", to="users.permissionblock"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("ADMIN", "Admin"), ("TECHNICIAN", "Technician"), ("CLIENT", "Client")], default="ADMIN", max_length=30),
        ),
        migrations.RunPython(normalize_existing_roles, migrations.RunPython.noop),
    ]
