# Generated by Django 5.2.15 on 2026-06-30 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_theme_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="technical_group",
        ),
    ]
