# Generated by Django 6.0.5 on 2026-05-13 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('requester', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='Atendimento', max_length=80)),
                ('type', models.CharField(blank=True, default='Incidente', max_length=80)),
                ('priority', models.CharField(choices=[('Crítica', 'Crítica'), ('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=30)),
                ('impact', models.CharField(default='Médio', max_length=30)),
                ('urgency', models.CharField(default='Média', max_length=30)),
                ('status', models.CharField(choices=[('Triagem', 'Triagem'), ('Em atendimento', 'Em atendimento'), ('Aguardando cliente', 'Aguardando cliente'), ('Validação', 'Validação'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado')], default='Triagem', max_length=40)),
                ('team', models.CharField(blank=True, default='', max_length=120)),
                ('sla', models.CharField(blank=True, default='8h', max_length=30)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('est_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('done_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
