# Generated by Django 6.0.5 on 2026-05-13 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
