# Generated by Django 4.0.3 on 2026-05-26 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_sprint_activity_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_ticket_configuration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsible_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='sprints.sprint'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='impact',
            field=models.CharField(default='Medio', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Critica', 'Critica'), ('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], default='Media', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Triagem', 'Triagem'), ('Aguardando atendimento', 'Aguardando atendimento'), ('Em atendimento', 'Em atendimento'), ('Aguardando cliente', 'Aguardando cliente'), ('Validacao', 'Validacao'), ('Pausado', 'Pausado'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(default='Media', max_length=30),
        ),
    ]
