# Generated by Django 4.0.3 on 2026-05-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ticket_contact_responsible_ticket_requester_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="contact_responsible_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ticket",
            name="contact_responsible_phone",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
