# Generated by Django 5.2.15 on 2026-06-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_custom_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="rating_comment",
            field=models.TextField(blank=True),
        ),
    ]
