# Generated by Django 5.2.15 on 2026-06-23 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_auto_assign"),
        ("tickets", "0011_alter_ticket_rating_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="csat_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="last_reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reopen_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reopen_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="impact",
            field=models.CharField(
                choices=[("Alto", "Alto"), ("Médio", "Médio"), ("Baixo", "Baixo")],
                default="Médio",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="type",
            field=models.CharField(
                choices=[
                    ("Incidente", "Incidente"),
                    ("Requisição", "Requisição"),
                    ("Problema", "Problema"),
                    ("Mudança", "Mudança"),
                    ("Outro", "Outro"),
                ],
                default="Incidente",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="urgency",
            field=models.CharField(
                choices=[("Alta", "Alta"), ("Média", "Média"), ("Baixa", "Baixa")],
                default="Média",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TicketStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "changed_by_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status_from",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("status_to", models.CharField(max_length=60)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_status_histories",
                        to="companies.company",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
                "unique_together": {("company", "weekday")},
            },
        ),
        migrations.CreateModel(
            name="CompanyHoliday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("company", "date")},
            },
        ),
        migrations.CreateModel(
            name="TicketRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("duplicado", "Duplicado de"),
                            ("relacionado", "Relacionado a"),
                            ("bloqueia", "Bloqueia"),
                            ("bloqueado_por", "Bloqueado por"),
                        ],
                        default="relacionado",
                        max_length=30,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_relations",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ticket_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_by",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("ticket", "related_ticket", "relation_type")},
            },
        ),
    ]
