# Generated by Django 5.2.15 on 2026-06-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_active_client_address_client_document_and_more"),
        ("tickets", "0012_ticket_csat_sent_at_ticket_last_reopened_at_and_more"),
        ("users", "0009_remove_technical_group_add_teams_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="slapolicy",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sla_policies",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("portal", "Portal"),
                    ("email", "E-mail"),
                    ("chat", "Chat"),
                    ("telefone", "Telefone"),
                    ("api", "API"),
                ],
                default="portal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="clients.client",
            ),
        ),
    ]
