# Generated by Django 5.2.15 on 2026-06-30 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_org_structure_v2"),
        ("tickets", "0013_org_structure_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundMailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("webhook_token", models.CharField(max_length=128, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("on_create", "Ao criar chamado"),
                            ("on_update", "Ao atualizar chamado"),
                            ("on_status_change", "Ao mudar status"),
                            ("on_sla_breach", "Ao violar SLA"),
                        ],
                        default="on_create",
                        max_length=40,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=list)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("set_priority", "Definir prioridade"),
                            ("set_status", "Definir status"),
                            ("assign_technician", "Atribuir técnico"),
                            ("assign_team", "Atribuir equipe"),
                            ("add_tag", "Adicionar tag"),
                            ("send_notification", "Enviar notificação"),
                        ],
                        max_length=40,
                    ),
                ),
                ("action_value", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
