# Generated by Django 5.2.15 on 2026-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0015_ticket_resolution_notes_ticket_resolution_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketrelation",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("duplicado", "Duplicado de"),
                    ("relacionado", "Relacionado a"),
                    ("bloqueia", "Bloqueia"),
                    ("bloqueado_por", "Bloqueado por"),
                    ("subchamado", "Subchamado de"),
                ],
                default="relacionado",
                max_length=30,
            ),
        ),
    ]
