# Generated by Django 5.2.15 on 2026-07-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0016_alter_ticketrelation_relation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketrelation",
            name="blocks_parent",
            field=models.BooleanField(default=False),
        ),
    ]
