# Generated by Django 5.2.15 on 2026-07-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0017_ticketrelation_blocks_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketworkflowstatus",
            name="item_type",
            field=models.CharField(
                choices=[("ticket", "Chamado"), ("activity", "Atividade")],
                default="ticket",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticketworkflowstatus",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ticketworkflowstatus",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entrada", "Entrada"),
                    ("triagem", "Triagem"),
                    ("aprovacao", "Aprovação"),
                    ("atendimento", "Atendimento"),
                    ("aguardando_terceiro", "Aguardando terceiro"),
                    ("validacao", "Validação"),
                    ("pausado", "Pausado"),
                    ("final", "Final"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="ticketworkflowstatus",
            name="requirements",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
