# Generated by Django 5.2.15 on 2026-07-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0018_ticketworkflowstatus_item_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aberto", "Aberto"),
                    ("Aguardando Aprovacao", "Aguardando Aprovacao"),
                    ("Aprovado", "Aprovado"),
                    ("Reprovado", "Reprovado"),
                    ("Ajustes Solicitados", "Ajustes Solicitados"),
                    ("Triagem", "Triagem"),
                    ("Aguardando atendimento", "Aguardando atendimento"),
                    ("Em atendimento", "Em atendimento"),
                    ("Aguardando cliente", "Aguardando cliente"),
                    ("Validacao", "Validacao"),
                    ("Pausado", "Pausado"),
                    ("Cancelado", "Cancelado"),
                    ("Finalizado", "Finalizado"),
                    (
                        "Convertido em Atividade de Projeto",
                        "Convertido em Atividade de Projeto",
                    ),
                ],
                default="Aberto",
                max_length=40,
            ),
        ),
    ]
