# Generated by Django 5.2.15 on 2026-07-09 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_org_structure_v2"),
        ("tickets", "0020_ticket_backlog_to_triagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="team_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="teams.team",
            ),
        ),
    ]
