# Generated by Django 5.2.15 on 2026-07-11 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_org_structure_v2"),
        ("tickets", "0021_ticket_team_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="affected_service",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="ticket",
            name="preferred_contact_channel",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="ticket",
            name="preferred_contact_time",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="ticket",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="subcategories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="TicketPortalFormConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("fields", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_form_config",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
