# Generated by Django 5.2.15 on 2026-07-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0022_ticket_affected_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slapolicy",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="attachment_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="subcategory_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticketcustomfield",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_fields",
                to="tickets.ticketcategory",
            ),
        ),
        migrations.AddField(
            model_name="ticketcustomfield",
            name="visible_to_client",
            field=models.BooleanField(default=False),
        ),
    ]
