from django.urls import path, include

urlpatterns = [
    path("auth/", include("apps.authentication.urls")),
    path("", include("apps.dashboard.urls")),
    path("companies/", include("apps.companies.urls")),
    path("users/", include("apps.users.urls")),
    path("permission-blocks/", include("apps.users.permission_block_urls")),
    path("departments/", include("apps.users.department_urls")),
    path("positions/", include("apps.users.position_urls")),
    path("clients/", include("apps.clients.urls")),
    path("organizations/", include("apps.clients.urls")),
    path("projects/", include("apps.projects.urls")),
    path("tickets/", include("apps.tickets.urls")),
    path("ticket-categories/", include("apps.tickets.category_urls")),
    path("ticket-workflow-statuses/", include("apps.tickets.workflow_status_urls")),
    path("ticket-comments/", include("apps.tickets.comment_urls")),
    path("ticket-attachments/", include("apps.tickets.attachment_urls")),
    path("ticket-approvals/", include("apps.tickets.approval_urls")),
    path("sprints/", include("apps.sprints.urls")),
    path("sprint-activity-plans/", include("apps.sprints.plan_urls")),
    path("activities/", include("apps.activities.urls")),
    path("activity-tags/", include("apps.activities.tag_urls")),
    path("activity-time-entries/", include("apps.activities.time_entry_urls")),
    path("activity-comments/", include("apps.activities.comment_urls")),
    path("activity-attachments/", include("apps.activities.attachment_urls")),
    path("notifications/", include("apps.notifications.urls")),
    path("notification-preferences/", include("apps.notifications.preference_urls")),
    path("audit-logs/", include("apps.audit.urls")),
    path("knowledge/", include("apps.knowledge.urls")),
    path("communication/", include("apps.communication.urls")),
    path("search/", include("apps.search.urls")),
    path("", include("apps.forum.urls")),
    path("", include("apps.doubts.urls")),
    path("email-templates/", include("apps.notifications.email_template_urls")),
    path("sla-policies/", include("apps.tickets.sla_urls")),
    path("reports/", include("apps.reports.urls")),
    path("webhooks/", include("apps.webhooks.urls")),
    path("superadmin/", include("config.superadmin_urls")),
]
