# Generated by Django 5.2.15 on 2026-06-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_active_client_address_client_document_and_more"),
        ("communication", "0004_forumbadge_userbadge"),
        ("projects", "0005_projectcustomfield_projectcustomvalue"),
        ("tickets", "0012_ticket_csat_sent_at_ticket_last_reopened_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_conversations",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_conversations",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_conversations",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("direto", "Conversa direta"),
                    ("grupo", "Grupo"),
                    ("chamado", "Vinculado a chamado"),
                    ("projeto", "Vinculado a projeto"),
                    ("entidade", "Canal de entidade/cliente"),
                ],
                default="direto",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="forumcategory",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forum_categories",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="forumtopic",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("interna", "Interna (só colaboradores)"),
                    ("publica_cliente", "Pública para clientes vinculados"),
                    ("todos", "Todos"),
                ],
                default="todos",
                max_length=20,
            ),
        ),
    ]
