# Generated by Django 5.2.15 on 2026-07-09 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0005_org_structure_v2"),
        ("tickets", "0020_ticket_backlog_to_triagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumtopic",
            name="converted_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_forum_topics",
                to="tickets.ticket",
            ),
        ),
    ]
