# Generated by Django 5.2.15 on 2026-07-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0006_forumtopic_converted_ticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("aguardando_atendente", "Aguardando atendente"),
                    ("em_atendimento", "Em atendimento"),
                    ("aguardando_cliente", "Aguardando cliente"),
                    ("encerrada", "Encerrada"),
                ],
                default="aberta",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("direto", "Conversa direta"),
                    ("grupo", "Grupo"),
                    ("suporte", "Atendimento ao cliente"),
                    ("chamado", "Vinculado a chamado"),
                    ("projeto", "Vinculado a projeto"),
                    ("entidade", "Canal de entidade/cliente"),
                ],
                default="direto",
                max_length=20,
            ),
        ),
    ]
