# Generated by Django 5.2.15 on 2026-06-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("clients", "0002_client_active_client_address_client_document_and_more"),
        ("users", "0009_remove_technical_group_add_teams_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="users.department",
            ),
        ),
    ]
