# Generated by Django 6.0.5 on 2026-05-13 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('sector', models.CharField(blank=True, default='', max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('plan', models.CharField(blank=True, default='Pro', max_length=80)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('health', models.CharField(blank=True, default='Bom', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Ativo', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
