# Generated by Django 4.0.3 on 2026-05-26 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='client',
            name='organization_type',
            field=models.CharField(choices=[('CLIENTE_EMPRESA', 'Cliente empresa'), ('CLIENTE_PESSOA', 'Cliente pessoa'), ('EMPRESA_INTERNA', 'Empresa interna'), ('SETOR_INTERNO', 'Setor interno'), ('DEPARTAMENTO', 'Departamento'), ('FILIAL', 'Filial'), ('OUTRO', 'Outro')], default='CLIENTE_EMPRESA', max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='clients.client'),
        ),
    ]
