# Generated by Django 5.2.15 on 2026-06-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_active_client_address_client_document_and_more"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="clients",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_teams", to="clients.client"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subgroups",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("equipe", "Equipe de execução (Sprint/Projeto)"),
                    ("grupo", "Grupo organizacional (Atribuição/Permissão)"),
                ],
                default="equipe",
                max_length=20,
            ),
        ),
    ]
