# Generated by Django 5.2.15 on 2026-07-06 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_activitycustomfield_activitycustomvalue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="last_reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="reopen_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="resolution_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="activity",
            name="resolution_type",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="activity",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="status_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="note_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Resposta pública"),
                    ("internal", "Comentário interno"),
                    ("technical", "Nota técnica"),
                    ("resolution", "Resolução"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
