# Generated by Django 5.2.15 on 2026-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_email_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("Chamados", "Chamados"),
                    ("Aprovacoes", "Aprovacoes"),
                    ("Projetos", "Projetos"),
                    ("Atividades", "Atividades"),
                    ("Comentarios", "Comentarios"),
                    ("Sistema", "Sistema"),
                    ("Forum", "Forum"),
                ],
                default="Sistema",
                max_length=30,
            ),
        ),
    ]
